<a href="https://colab.research.google.com/github/SRINITHIN-S/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ls=[10,20,30,40]

In [ ]:
arr=np.array(ls)

In [ ]:
arr

array([10, 20, 30, 40])

In [ ]:
arr.shape

(4,)

In [ ]:
arr[1:5]

array([20, 30, 40])

In [ ]:
arr[1:2]=100

In [ ]:
arr

array([ 10, 100,  30,  40])

In [ ]:
np.shape(arr)

(4,)

In [ ]:
np.reshape(arr,(2,2))

array([[ 10, 100],
       [ 30,  40]])

In [ ]:
arr

array([ 10, 100,  30,  40])

In [ ]:
arr.ndim

1

In [ ]:
narr=np.reshape(arr,(2,2))

In [ ]:
narr

array([[ 10, 100],
       [ 30,  40]])

In [ ]:
arr

array([ 10, 100,  30,  40])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])